### ISSUE TITLE
Egeria 3.3 prerelease chart - egeria-ui does not load

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-charts#73] opened 2021-10-12 10:51 UTC
In the egeria 3.3 prerelease (.2) chart, the Egeria UI is not loading under either OpenShift 4.8 or microk8s (macOS)

In both cases, going to the nginx-server endpoint results in a single webpage showing 'Loading ...'

* The nginx container looks ok and is showing page loads. See https://gist.github.com/05f5833105da7b59cb5687f3fff012ab
* The ui-chassis container has the regular 'ready' message, no errors seen. See https://gist.github.com/5311f2d064ff1c69fd187476b211b0c1
* The static ui container also looks ok, and is serving pages as expected. see https://gist.github.com/95dcae9bad53851153cada5e5582d5d3

It's possible there is a version discrepancy. Egeria ui chassis/egeria is at 3.3-SNAPSHOT, whilst egeria-ui is at 3.0.1
Note that this is the latest release (from August) as tested with egeria 3.2. However the release version is still set to 3.0.1 in main, meaning the images are constantly being updated rather than being set to a future prerelease (though this may not be the cause of this issue)

@lpalashevski @sarbull can you take a look? Let me know if you need anything. If we are to have the UI enabled for 3.3 we need to get a stable UI configuration in the charts.

**Comment by lpalashevski** [comment] 2021-10-14 08:59
The issue is now fixed with https://github.com/odpi/egeria-ui/pull/249. I have tested the lab chart locally on my local k8s; works as expected.
Since we all agreed, we are going to properly test it and release the charts using stable static ui image version.
Lets chat on the call.

**Closed as completed** 2021-10-27 09:35 UTC
